name: Dev environment tests

on:
  workflow_run:
    workflows: ["test listener"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      mock_run:
        description: 'Indicates that the run is mock or not'
        required: false
        default: true
        type: 'boolean'

jobs:
  wait-for-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for dev deployment to complete
        run: |
          if [ ${{ inputs.mock_run }} ]; then
            echo "this is mock run"
          else
            echo "Set sleep for 10 sec"
            sleep 10
          fi

  run-automation-tests:
    needs: wait-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "dooone"
