name: Random Exit Code with Sleep (Triggered from another Repo)

on:
  repository_dispatch:
    types: [trigger-exit]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: testing-step
      run: echo "im a testesr"

  random-failure-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print event type
      run: |
        echo "The event type is: ${{ github.event.action }}"
    - name: Display caller information
      run: |
        echo "This workflow was triggered by another workflow."
        echo "Caller workflow name: ${{ github.event.workflow }}"
        echo "Caller repository: ${{ github.event.repository.full_name }}"
        echo "Caller ref: ${{ github.event.ref }}"
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Randomly drop exit code
      run: |
        # Generate a random number (0 or 1)
        RANDOM_EXIT_CODE=0

        echo "Generated exit code: $RANDOM_EXIT_CODE"
        exit 0
