name: pr-test

on:
  pull_request: 
    types: [opened, synchronize, reopened]
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        run: echo "test"
