name: test test

on:
  workflow_dispatch:
    inputs:
      mock_run:
        description: 'Indicates the mock run'
        required: false
        default: true
        type: 'boolean'

jobs:
  wait-for-deployment:
    if: ${{ inputs.mock_run == 'false' }} # Run only if not a mock run
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo "first"

  run-automation-tests:
    needs: wait-for-deployment
    if: ${{ needs.wait-for-deployment.result == 'success' || needs.wait-for-deployment.result == 'skipped' }} # Only run if first succeeds or is skipped
    runs-on: ubuntu-latest
    steps:
      - name: second
        run: echo "second"
