name: Default Push Pipeline

on:
  push:
    branches: [ test ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        run: echo "test"
