name: test test

on:
  workflow_dispatch:
    inputs:
      mock_run:
        description: 'Indicates the mock run'
        required: false
        default: true
        type: 'boolean'

jobs:
  wait-for-deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.mock_run == 'false' }}
    steps:
      - name: first
        run: echo "first"

  run-automation-tests:
    runs-on: ubuntu-latest
    needs: [ wait-for-deployment ]
    if: ${{ needs.wait-for-deployment.result == 'skipped' || needs.wait-for-deployment.result == 'success' }}
    steps:
      - name: second
        run: echo "second"
