name: Update Module Version in Terragrunt

on:
  repository_dispatch:
    types: [module-release]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Extract Info
        run: |
          TAG="${{ github.event.client_payload.tag }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          MODULE=$(echo "$TAG" | cut -d'-' -f1)
          VERSION=$(echo "$TAG" | cut -d'-' -f2-)
          echo "MODULE=$MODULE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Update terragrunt.hcl
        id: update_file
        run: |
          FILE=$(find live -path "*/${MODULE}/terragrunt.hcl" | head -1)
          if [ -z "$FILE" ]; then
            echo "No terragrunt file found for module $MODULE"
            echo "CHANGES=false" >> $GITHUB_ENV
            exit 0
          fi
          echo "Updating $FILE to version $VERSION"
          sed -i "s|ref=${MODULE}-v[^\"']*|ref=${MODULE}-${VERSION}|g" "$FILE"
          git diff --exit-code > /dev/null
          if [ $? -eq 0 ]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_ENV
          else
            echo "CHANGES=true" >> $GITHUB_ENV
          fi
          
      - name: Create Pull Request
        if: env.CHANGES == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: "chore: bump ${{ env.MODULE }} to ${{ env.MODULE }}-${{ env.VERSION }}"
          branch: bump-${{ env.MODULE }}-${{ env.VERSION }}
          delete-branch: true
          title: "Update ${{ env.MODULE }} to ${{ env.MODULE }}-${{ env.VERSION }}"
          body: |
            This PR updates ${{ env.MODULE }} to tag `${{ env.MODULE }}-${{ env.VERSION }}`.
