name: "build: mvn build and put image in GCR"
# Controls when the workflow will run
on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: test
        run: ls -la
